NDefines.NDiplomacy.IMPERIAL_AUTHORITY_FROM_PRINCES = 0.15
NDefines.NDiplomacy.HRE_FOREIGN_CONTROL_PENALTY = -0.0075
NDefines.NDiplomacy.HRE_HERETIC_PENALTY = -0.005
NDefines.NMilitary.COSSACKS_SHOCK_DAMAGE_BONUS = 0.0