# This is a basic workflow to help you get started with Actions

name: Early Access Builds

# Controls when the workflow will run
on:
  # Triggers the workflow on any tags, we usually do not have any tags as we do not
  # provide .zip files
  push:
    tags: '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  mod: post-finem-${{ github.ref_name }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"  build:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Zip Europa Universalis IV mod
        id: zip
        uses: maxice8/eu4-mod-zip@v0.0.4
        with:
          mod-name: ${{ env.mod }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.mod }}
          path: ${{ steps.zip.outputs.zip-path }}

  release:
    needs: build

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download
        id: download
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.mod }}
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.mod }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
    
  # Remove old releases
  remove:
    needs: release

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Delete Older Releases
        uses: dev-drprasad/delete-older-releases@v0.2.1

        with:
          keep_latest: 3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

